### ISSUE TITLE
image uvms/wildfly-full:lates t not found.

### ISSUE THREAD

**Issue by gkgeorgiev** [UnionVMS/UVMS-Docker#2]
I tried to specify version 2.1.0 and 2.1.1 as recommended by Joakim, but still it doesn't find wildfly-full image. See the logs:
> Unable to find image 'uvms/wildfly-full:latest' locally
> Pulling repository docker.io/uvms/wildfly-full
> C:\Program Files\Docker Toolbox\docker.exe: Error: image uvms/wildfly-full:lates
> t not found.
> See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
> 
> georgige@GEORGIGE2 MINGW64 /c/dev/git/UVMS-Docker (master)

**Comment by uvms** [comment]
The simple answer is that there is no uvms/wildfly-full att the docker repo. Most likely the image you are looking for is uvms/wildfly-release:2.1.1

uvms/wildfly-full is the tag used by build.bat and run.bat for the image based on the latest snapshots, so that is not on the repo. However we have discussed setting up a nightly build for that, but that lies in the future.

**Comment by gkgeorgiev** [comment]
thx, now I got it :)
